# Generated by Django 5.2.17 on 2026-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('card', 'Card'), ('online_transfer', 'Online Transfer'), ('other', 'Other')], max_length=40),
        ),
    ]
